### ISSUE TITLE
Restructure the models to match the new documentation

### ISSUE THREAD

**Issue by anguslmm** [anguslmm/pullupsforpatriots#26]
The models have been changed in [the model document](../blob/master/docs/modeldescription.md). Make the models match that.

Don't forget to `makemigrations` when you update the model, and don't forget to `migrate` before running the server after the model has been updated.

**Comment by questornot** [comment]
yo i will do the command model no one else do it KAY ?

**Comment by drayc99** [comment]
haha I already did it

**Comment by questornot** [comment]
DAMN THWARTED ONCE AGAIN
